### ISSUE TITLE
Cloud deployment succeeds but Web App unreachable

### ISSUE THREAD

**Issue by ddjidel** [Azure/azure-iot-predictive-maintenance#16]
My deployment in Azure succeeds but ends with that warning: "website unable to resolve https://predictivecrm.azurewebsites.net". The solution dashboard is indeed unreachable while everything looks fine in Azure (see attached screenshots).

I might be missing something but can't figure out what...
![azure services](https://cloud.githubusercontent.com/assets/537895/12262349/c1a03050-b927-11e5-9ac4-b0a62ff88987.png)
![dashboard 1](https://cloud.githubusercontent.com/assets/537895/12262350/c1b75352-b927-11e5-8b43-de43da38c1e5.png)
![dashboard 2](https://cloud.githubusercontent.com/assets/537895/12262347/c11222a6-b927-11e5-84cc-27a98ce3964a.png)
![log](https://cloud.githubusercontent.com/assets/537895/12262348/c138561a-b927-11e5-89dd-70fc78a57298.png)
![solution](https://cloud.githubusercontent.com/assets/537895/12262346/c110ad36-b927-11e5-8c98-13d0cdffc6f0.png)

**Comment by aguilaaj** [comment]
Hi @ddjidel - can you shoot us a mail at iotsolhelp@microsoft.com for further investigation? Thanks!

**Comment by ddjidel** [comment]
Hi Ariel,
Thanks for the reply. I'm currently preparing an email that I will send from my Microsoft account (I'm a Dynamics CRM TSP working at Microsoft in Switzerland) with all the explanations about what I'm trying to achieve, so you will get the full picture. You should get it by 30mn. Is that ok for you?
Thanks

Date: Tue, 12 Jan 2016 10:58:52 -0800

**Comment by aguilaaj** [comment]
Great, looking forward to it. Thanks!

**Comment by jamesweb-ms** [comment]
Looks like this was resolved offline.  There can be a delay between provisioning and when a website DNS name is available.  This can be up to an hour if the HostNotFound is cached in your local DNS server.
