### ISSUE TITLE
How to address this error message? Version 0.9.6; update to 1.0.3 and run again.

### ISSUE THREAD

**Issue by Abdelkrim** [Azure/azure-iot-predictive-maintenance#25]
Run `C:\azure-iot-predictive-maintenance\build.cmd local`

**An error message appears:**

C:\azure-iot-predictive-maintenance>C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPo
licy Unrestricted -Command C:\azure-iot-predictive-maintenance\\Common\Deployment\PrepareIoTSample.ps1 -en
vironmentName local -configuration Debug
Version 0.9.6; update to 1.0.3 and run again.
At C:\azure-iot-predictive-maintenance\Common\Deployment\DeploymentLib.ps1:1148 char:5
+     throw "Version $($module.Version.Major).$($module.Version.Minor).$($module.V ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Version 0.9.6; ... and run again.:String) [], RuntimeException
    + FullyQualifiedErrorId : Version 0.9.6; update to 1.0.3 and run again.

Error C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Unrestricted -Command C:\
azure-iot-predictive-maintenance\\Common\Deployment\PrepareIoTSample.ps1 -environmentName local -configuration Debug
Arguments: build.cmd "Command" "Configuration" "EnvironmentName" "ActionType"
  Command: build (just builds); local (config local); cloud (config cloud, build, and deploy)
  Configuration: build configuration either Debug or Release; default is Debug
  EnvironmentName: Name of cloud environment to deploy - default is local
ECHO is on.
eg.
  build - build.cmd build
  local deployment: build.cmd local
  cloud deployment: build.cmd cloud release mydeployment

**Comment by wesselkranenborg** [comment]
You can just do what the error message says:
> Version 0.9.6; update to 1.0.3 and run again.

Update your Azure SDK to minimal 1.0.3 and run again.

**Comment by Abdelkrim** [comment]
thank you, it wasn't so clear that Azure had to be updated ;-)
