### ISSUE TITLE
 FullyQualifiedErrorId : Unable to create workspace 'LocalPM'

### ISSUE THREAD

**Issue by Abdelkrim** [Azure/azure-iot-predictive-maintenance#26]
* run ```build.cmd local```

an error occurred after having selected the storage location and my account: " FullyQualifiedErrorId : Unable to create workspace 'LocalPM'"

Could you tell me what to do? restart everything? 

Successfully assigned user to application 'localApp' as role 'Admin'
2016-04-02T02:10:46.4617031+02:00 - Added AADTenant with value 7d92164d81b0
2016-04-02T02:10:46.4757039+02:00 - Added AADMetadataAddress with value https://login.windows.net/7d92164d/FederationMetadata/2007-06/FederationMetadata.xml
2016-04-02T02:10:46.4887046+02:00 - Added AADAudience with value https://localhost:44305/iotsuite
2016-04-02T02:10:46.4967051+02:00 - Added AADRealm with value https://localhost:44305/iotsuite
2016-04-02T02:10:46.6037112+02:00 - Creating ML workspace: LocalPM
2016-04-02T02:10:47.2477480+02:00 - Creating new storage account: mllocalpme10e6

Unable to create workspace 'LocalPM'
At C:\dev\ro-github\azure-iot-predictive-maintenance\Common\Deployment\DeploymentLib.ps1:639 char:13
+             throw ("Unable to create workspace '{0}'" -f $name)
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Unable to create workspace 'LocalPM':String) [], RuntimeException
    + FullyQualifiedErrorId : Unable to create workspace 'LocalPM'

Error C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Unrestricted -Command C:\dev\ro-github\
azure-iot-predictive-maintenance\\Common\Deployment\PrepareIoTSample.ps1 -environmentName local -configuration Debug
Arguments: build.cmd "Command" "Configuration" "EnvironmentName" "ActionType"
  Command: build (just builds); local (config local); cloud (config cloud, build, and deploy)
  Configuration: build configuration either Debug or Release; default is Debug
  EnvironmentName: Name of cloud environment to deploy - default is local
ECHO is on.
eg.
  build - build.cmd build
  local deployment: build.cmd local
  cloud deployment: build.cmd cloud release mydeployment

**Comment by aguilaaj** [comment]
Make sure you set up all the requirements: 
https://github.com/Azure/azure-iot-predictive-maintenance/wiki/Set-up-development-environment-%28Windows%29

**Comment by aguilaaj** [comment]
@Abdelkrim - were you able to resolve your issue?

**Comment by aguilaaj** [comment]
Closing for now, please re-open if still having issues.
