### ISSUE TITLE
Unable to generate SAS token for uploaded build release on blob storage

### ISSUE THREAD

**Issue by zhang-hua** [Azure/azure-iot-predictive-maintenance#43]
The SAS token is supposedly generated here: 
https://github.com/Azure/azure-iot-predictive-maintenance/blob/master/Common/Deployment/DeploymentLib.ps1#L458
But it is empty and fail the websites provisioning with conflict state in CLI deployment.

**Comment by miwolfms** [comment]
As of December 10th 2020, Predictive Maintenance solution accelerator is no longer supported. All supporting repositories have been archived.
