### ISSUE TITLE
Authorization error while accessing ML studio workspace or Launching the application

### ISSUE THREAD

**Issue by sakimsft** [Azure/azure-iot-predictive-maintenance#49]
Step to reproduce:
1. Create a PdM solution from https://www.azureiotsolutions.com/Accelerators
2. Launch application
3. Access Azure ML studio workspace

Expected behavior:
Access both Azure ML studio workspace and Launch application without an issue.

Actual behavior:
If MSFT tenant is used, launching application fails with authorization error.
If non MSFT tenant is used, accessing ML studio workspace fails with authorization error.

**Comment by miwolfms** [comment]
As of December 10th 2020, Predictive Maintenance solution accelerator is no longer supported. All supporting repositories have been archived.
