### ISSUE TITLE
doesn't deploy to cloud

### ISSUE THREAD

**Issue by ac2707** [Azure/azure-iot-predictive-maintenance#50]
Pulled the code for this and within VS 2017 professional ran the  command for  cloud deploy as below:
![image](https://user-images.githubusercontent.com/49182510/58615053-bfdcaa00-82d7-11e9-88c1-820997bd58e0.png)
please advise as to what is missing.

**Comment by ac2707** [comment]
this worked with the typescript installation.

**Comment by ac2707** [comment]
Provisioning failed - deployed to West US -
please advise.

![image](https://user-images.githubusercontent.com/49182510/58621890-f9b5ac80-82e7-11e9-8680-e542069be8d8.png)

**Comment by ac2707** [comment]
Any update on this ? Please advise, Thanks

**Comment by miwolfms** [comment]
As of December 10th 2020, Predictive Maintenance solution accelerator is no longer supported. All supporting repositories have been archived.
