### ISSUE TITLE
Failure when creating mlworkspace

### ISSUE THREAD

**Issue by HandlessPianist** [Azure/azure-iot-predictive-maintenance#51]
Hello, while trying to run the build.cmd on my windows machine i got the following error:

![image](https://user-images.githubusercontent.com/16084034/79463703-784b3380-7ff9-11ea-92dd-1dbd220032f5.png)

I am running the recommended versions, with VS2015.

Is this due to a change in the API signature?

**Comment by miwolfms** [comment]
As of December 10th 2020, Predictive Maintenance solution accelerator is no longer supported. All supporting repositories have been archived.
